# Generated by Django 4.2.17 on 2025-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241228_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=255, unique=True),
        ),
    ]
